version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - echo "Repo URI: $REPOSITORY_URI"
      - aws sts get-caller-identity
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI 

  build:
    commands:
      - mvn clean package
      - docker build -t springboot-app .
      - docker tag springboot-app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"springboot-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
